### PR TITLE
Analysis of expressed cells

### PR DESCRIPTION
**Pull request by jhsiao999**

### CODE REVIEW

**Comment by jdblischak** [comment]
`cv.rda` is in `../data/`. These files point to `rda/cv-adjusted-summary-pois-expressed/`. Could you please update the path? Also I've been making small changes to the data files, and these changed the total number of genes and samples. Could you please update `cv.rda` with the new data? Thanks!

**Comment by jhsiao999** [comment]
Ooops! I am also updating some analyses in cv-adjusted-summary-pois-expressed.Rmd. I'll push the file after incorporating these changes.

**Comment by jhsiao999** [comment]
After re-ran some of the analyses, I found that the number of genes has increased from ~12,000 to ~13,000 in the filtered data. Is this correct?

**Comment by jdblischak** [comment]
Correct. There are now 12,584 after filtering. The increase is due to changing the mapper.

**Pull request merged**
